### ISSUE TITLE
質問カードの作成

### ISSUE THREAD

**Issue by pantasystem** [Calorie-Friends/qomalin_app#8]
質問を表示するためのQuestionCardを作成する。
QuestionCardはStatelessWidgetを継承する。
フィールドに以下のものを持つ
* final String title
* final String text
* final String? avatarIcon
* final String username
* final VoidCallback onQuestionPressed
* final VoidCallback onUserPressed

## 仕様
投稿の内容を簡易表示する。
タイトル(title), 本文(text), ユーザーのアイコン(avatarIcon), ユーザー名(username)を表示する。
本文は二行だけ表示する。

また投稿をクリックした時リップルを表示した上でonQuestionPressed関数を呼び出す。
ユーザーのアイコンをクリックした時にユーザーアイコン上でリップルを表示した上でonUserPressed関数を呼び出す。

**Comment by Kinoshita0623** [comment]
HomePageにタブを作成する
タブには「近く」と「最新」の項目を作成する。
